### PR TITLE
Task

### PR DESCRIPTION
**Pull request by mpinka**

### CODE REVIEW

**Comment by himdel** [comment]
- [x] git rebase master - solving conflicts **3pts**
- [x] git rebase -i master (squash) **3pts**
- [x] git rebase -i master (reword) **2pts**
- [x] git rebase -i master (drop) **1pts**
- [x] git rebase -i master (edit) **2pts**
- [x] one of instructor mentioned **1.5pts**

= 12.5 points

**Comment by mpinka** [comment]
Hey,

Whats wrong,
I solved conflicts what was resolved mistakenly?
You didnt say anything about mentioning instructor in pull request :/. Did i miss something? Or how did you mean it?

Martin Pinka



31. 10. 2017 v 16:38, Martin Hradil <notifications@github.com>:

**Comment by himdel** [comment]
> I solved conflicts what was resolved mistakenly?

This branch has conflicts that must be resolved
Conflicting files
crinos9.md

Clearly not ;). It *looks* like you rebased against something else than upstream master, because your PR tries to change all the files back to how they were before - that's why it's always a good idea to look what changes you see on github ;).

But feel free to fix this, you can still get the points.


> You didnt say anything about mentioning instructor in pull request :/. Did i miss something? Or how did you mean it?

I did mention that you need to read [the instructions](https://github.com/RoadToSoftwareFactory/swi1-2017-odd-git#swi1-2017-odd-git) ;) .. 

"10. when done mention one of instructors in a comment (if you are the first one to do everything correctly you will get a GitHub code for free t-shirt via Gitter)"

**Comment by mpinka** [comment]
@himdel its should be fixed now. Thanks for possibility of getting the points. I really dont know what happened that day :(.

**Comment by himdel** [comment]
No problem, glad you managed to fix it :) Updated the checklist to say 12.5 now :)

**Pull request closed without merging**
