### PR TITLE
Second

### PR DESCRIPTION
**Pull request by xcocul00**
PR for 8 commits

### CODE REVIEW

**Comment by xcocul00** [comment]
@himdel

**Comment by ZitaNemeckova** [comment]
- [ ] git rebase master - solving conflicts **3pts** not rebased against upstream/master
- [x] git rebase -i master (squash) **3pts**
- [x] git rebase -i master (reword) **2pts**
- [x] git rebase -i master (drop) **1pts**
- [x] git rebase -i master (edit) **2pts**
- [x] one of instructor mentioned **1.5pts**

**Comment by ZitaNemeckova** [comment]
Feel free to fix and get all points, if you want :)

**Comment by himdel** [comment]
@xcocul00 Looks like you used a `git merge`, which we will *not* be using in this course.

You may need to try again :).

---

If you want to try this at home, you can start from 92ca365 (instead of master), and then (once you have the first 8 commits), rebase on top of bddeed3 (instead of upstream/master).

So ... to get a really clean start, you would do something like:

```
git clone https://github.com/xcocul00/swi1-2017-odd-git.git
cd swi1-2017-odd-git
git remote add upstream https://github.com/RoadToSoftwareFactory/swi1-2017-odd-git.git
git fetch --all
git checkout -b new-branch 92ca365
....
git rebase bddeed3   # and the same when doing rebase -i
```

**Comment by xcocul00** [comment]
I am sorry I just tried something else. :D But I will fix rebase too.

**Pull request closed without merging**
