### PR TITLE
osuskyCommitCV2

### PR DESCRIPTION
**Pull request by PeterOsusky**

### CODE REVIEW

**Comment by PeterOsusky** [comment]
pull changes

**Comment by himdel** [comment]
- [x] git rebase master - solving conflicts **3pts**
- [x] git rebase -i master (squash) **3pts**
- [x] git rebase -i master (reword) **2pts**
- [x] git rebase -i master (drop) **1pts**
- [x] git rebase -i master (edit) **2pts**
- [x] one of instructor mentioned **1.5pts**

= 0 points, sorry :(

(But feel free to update the PR, you can still get the points.)

EDIT: 12.5 points :+1:

**Comment by PeterOsusky** [comment]
@himdel how can I edit commit with city? delete the original city commit and create new for Helsinki? thanks

**Comment by PeterOsusky** [comment]
@himdel hope thats alright now

**Comment by himdel** [comment]
@PeterOsusky perfect, thanks! :) Added the points :).

As for editing.. this was specifically about the `edit` action in interactive rebase. But looks like you managed :)

**Pull request closed without merging**
