### PR TITLE
xjakl personal info

### PR DESCRIPTION
**Pull request by xjakl**
Changed my personal info

### CODE REVIEW

**Comment by himdel** [comment]
- [ ] git rebase master - solving conflicts **3pts**
- [ ] git rebase -i master (squash) **3pts**
- [ ] git rebase -i master (reword) **2pts**
- [ ] git rebase -i master (drop) **1pts**
- [ ] git rebase -i master (edit) **2pts**
- [ ] one of instructor mentioned **1.5pts**

= 0 points, sorry :(

(But feel free to update the PR, you can still get the points.)

**Comment by xjakl** [comment]
Ouch.. :( I submitted 1 commit instead of 8 commits. I did not thought of 1 commit per line. There are many students in class and time has passed quickly until You helped all students.  I solved conflict and paid attention to interactive rebase, but It was almost 3 p.m. (20 minutes after schedule end of lesson) and I needed to go, so I had no time to fix it and rebase 8 commits.

**Comment by xjakl** [comment]
And it is not clear from tasks we had to create PR with these changes ...

**Comment by himdel** [comment]
@xjakl Sorry, no excuses, you could have asked :) But feel free to fix it, you'll still get the points :).

**Comment by xjakl** [comment]
Ok, thanks for this opportunity. I'll try asap, but not before friday..

**Comment by xjakl** [comment]
@himdel I think that's all :)
Edit: well, the commit with uppercase dissapeared :-O

**Comment by himdel** [comment]
@xjakl You may need to try again...

the PR starts with a "Test commit" which changes most of the file - should not be there

then it has a "added line to delete in next commit" - should not be there

then "deleted line - solved conflict" - deletes the new line, but also changes fruit

then "combination of 3 commits" - deletes a DO NOT DELETE line, adds a line about fruit (looks like a commit message?), and does not actually change the 3 foods

then "added favorite city" - looks like rebasing with edit didn't work, it still says Brno

then "changed commit with favorite city" cleans up a change from the pre-previous commit, and changes the city... so part of this should be merged with "added favorite city" and part with "combination of 3 commits"

and then there's the season where you already know the uppercase dissapeared :).

and last, there's the "changed change me line" commit, which adds 2 lines and should not be there.

---

If you want to try this at home, you can start from 92ca365 (instead of master), and then (once you have the first 8 commits), rebase on top of bddeed3 (instead of upstream/master).

So ... to get a really clean start, you would do something like:

```
git clone https://github.com/xjakl/swi1-2017-odd-git.git
cd swi1-2017-odd-git
git remote add upstream https://github.com/RoadToSoftwareFactory/swi1-2017-odd-git.git
git fetch --all
git checkout -b new-branch 92ca365
....
git rebase bddeed3   # and the same when doing rebase -i
```

**Comment by himdel** [comment]
Closing - replaced by https://github.com/RoadToSoftwareFactory/swi1-2017-odd-git/pull/45

**Pull request closed without merging**
