### PR TITLE
Xjakl clean start

### PR DESCRIPTION
**Pull request by xjakl**
Second GIT lecture new try.

### CODE REVIEW

**Comment by xjakl** [comment]
@himdel  I hope it's ok now. A descriptive commit message has limited length?

**Comment by himdel** [comment]
- [x] git rebase master - solving conflicts **3pts**
- [x] git rebase -i master (squash) **3pts**
- [x] git rebase -i master (reword) **2pts**
- [x] git rebase -i master (drop) **1pts**
- [x] git rebase -i master (edit) **2pts**
- [x] one of instructor mentioned **1.5pts**

= 12.5

~~Almost there :)~~
You didn't manage to edit a commit, since I still see Brno in dd3bf09, and only changed to Helsinki in e5724c4. (If you managed to do the edit right, it would have changed the original commit.)

EDIT: updated

**Comment by himdel** [comment]
> A descriptive commit message has limited length?

I wouldn't say so, no ... if you feel the need to use paragraphs and chapters, maybe the text should go elsewhere, but, I'd rather see a long descriptive commit message than just "Changed stuff" :).


Looking at ManageIQ/manageiq-ui-classic commits, most of them have very short messages

   * some just the one line description

```
    List Provisioned disk name as N/A if size_on_disk is not collected
```

   * some have description and an additional line:

```
    Remove custom buttons for tagging in OPS
    
    If x_button is fired do not set custom buttons.
```

   * and a few have longer descriptions:

```
    Amazon Docker Creds Visibility Based on Setting
    
    The visibility of the Amazon Docker Creds tab will be based on a true
    Settings value. The setting used is Settings.ems.ems_amazon.agent_coordinator.docker_l
ogin_required.
    If the value is false no tab is presented.
    
    This feature is implemented based on offline discussions around the original PR implem
enting
    the tab - #2525 with @Fryguy.
    This is the original desired functionality but it was not implemented in time for the 
4.6 cutoff.
```

Hope that helps :)

(But for the purpose of these git exercises, I looked at what the commit message said, if it was relevant it was correct, if there was some extra git stuff, it was wrong.)

**Comment by xjakl** [comment]
@himdel I changed dd3bf09 and dropped e5724c4
Thanks

**Comment by himdel** [comment]
@xjakl Looks good, thanks! :)

**Pull request closed without merging**
