### PR TITLE
Xprexta second

### PR DESCRIPTION
**Pull request by DavidPrexta**
Updated DavidPrexta.md

### CODE REVIEW

**Comment by DavidPrexta** [comment]
Both merge conflicts fixed by keeping changes from master.

**Comment by DavidPrexta** [comment]
@himdel

**Comment by ZitaNemeckova** [comment]
- [ ] git rebase master - solving conflicts **3pts** - you didn't rebase against upstream/master
- [x] git rebase -i master (squash) **3pts**
- [x] git rebase -i master (reword) **2pts**
- [x] git rebase -i master (drop) **1pts**
- [x] git rebase -i master (edit) **2pts**
- [x] one of instructor mentioned **1.5pts**

**Comment by ZitaNemeckova** [comment]
You can fix it and get all points, if you want :)

**Pull request closed without merging**
